name: Code Quality

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  quality-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout代码
      uses: actions/checkout@v4
      
    - name: 设置Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: 安装依赖
      run: npm ci
      
    - name: 代码风格检查
      run: npm run lint
      
    - name: 格式化检查
      run: npm run format:check
      
    - name: 文件大小检查
      run: |
        echo "检查扩展包大小..."
        npm run package
        zip_size=$(stat -c%s *.zip 2>/dev/null || echo "0")
        max_size=$((5 * 1024 * 1024)) # 5MB
        
        if [ "$zip_size" -gt "$max_size" ]; then
          echo "❌ 扩展包过大: ${zip_size} bytes (最大: ${max_size} bytes)"
          exit 1
        else
          echo "✅ 扩展包大小合适: ${zip_size} bytes"
        fi
        
    - name: 安全扫描
      run: |
        echo "执行安全扫描..."
        # 检查敏感信息
        if grep -r "password\|secret\|key" js/ --exclude-dir=node_modules --exclude="*.min.js" | grep -v "placeholder\|example\|test"; then
          echo "❌ 发现可能的敏感信息"
          exit 1
        fi
        echo "✅ 安全扫描通过"
        
    - name: 权限检查
      run: |
        echo "检查扩展权限..."
        node -e "
          const manifest = require('./manifest.json');
          const permissions = manifest.permissions || [];
          const dangerousPerms = ['tabs', 'webRequest', 'webRequestBlocking', 'proxy', 'debugger'];
          const found = permissions.filter(p => dangerousPerms.includes(p));
          if (found.length > 0) {
            console.log('⚠️ 发现敏感权限:', found.join(', '));
            console.log('请确保这些权限是必需的');
          } else {
            console.log('✅ 权限检查通过');
          }
        "
        
    - name: 生成质量报告
      run: |
        echo "## 代码质量报告" > quality-report.md
        echo "" >> quality-report.md
        echo "### 基本信息" >> quality-report.md
        echo "- 构建时间: $(date)" >> quality-report.md
        echo "- 提交: ${{ github.sha }}" >> quality-report.md
        echo "- 分支: ${{ github.ref_name }}" >> quality-report.md
        echo "" >> quality-report.md
        
        echo "### 文件统计" >> quality-report.md
        echo "- JS文件: $(find js/ -name '*.js' | wc -l)" >> quality-report.md
        echo "- CSS文件: $(find css/ -name '*.css' | wc -l)" >> quality-report.md
        echo "- HTML文件: $(find html/ -name '*.html' | wc -l)" >> quality-report.md
        echo "- 总代码行数: $(find js/ css/ html/ -name '*.js' -o -name '*.css' -o -name '*.html' | xargs wc -l | tail -1 | awk '{print $1}')" >> quality-report.md
        
    - name: 上传质量报告
      uses: actions/upload-artifact@v4
      with:
        name: quality-report
        path: quality-report.md
